### ISSUE TITLE
Ability to change the color and other props by message

### ISSUE THREAD

**Issue by Tofandel** [Aymkdn/v-snackbars#1]
Currently color is general, adding a way for a message to override all of the props of the snackbar by passing an array of object instead of an array of messages shouldn't be trivial

Eg:
```js
messages: [{props: {color: "red", timeout: 400}, message: "Message"}]
```

**Comment by Aymkdn** [comment]
I'll have to think about it. I'll check during the week.

**Comment by Aymkdn** [comment]
I introduced a new `objects` prop with v2.1.0

Check the [README](https://github.com/Aymkdn/v-snackbars/blob/master/README.md#objects) to know more!
