### ISSUE TITLE
Ability to use HTML in the message

### ISSUE THREAD

**Issue by tattdogg** [Aymkdn/v-snackbars#15]
Hi
It will allow to have multiple line snackbar (by using br) + style the message with bold/italic/etc

**Comment by Aymkdn** [comment]
You can already do it: 
```vue
<template v-slot:default="{ message }">
   <span v-html="message"></span>
</template>
```

Check the demo at https://codesandbox.io/s/v-snackbars-demo-forked-je27y?file=/src/App.vue:200-305

**Comment by tattdogg** [comment]
Hi
I completely forgot about the slots. It makes sense then.
Thank you.
