### ISSUE TITLE
Wrong height calculation

### ISSUE THREAD

**Issue by tattdogg** [Aymkdn/v-snackbars#16]
Hi
I found very strange issue. Looks like it's related to the snackbar height calculation.
https://codesandbox.io/s/v-snackbars-demo-forked-imf5y?file=/src/App.vue

**How to replicate:**
Add one more tag to v-combobox

**Result**
It displays three shackbars one above the other
![Screenshot_1](https://user-images.githubusercontent.com/15647102/115124949-df654480-9fcd-11eb-835e-c773476afade.jpg)

I will venture to suggest that somewhere in the code `this.$nextTick()` is missing

**Comment by Aymkdn** [comment]
The problem was due to the addition of several items at once. I've just published a fix for that.
