### ISSUE TITLE
Doesn't have clean up process for the disposed snackbars

### ISSUE THREAD

**Issue by tattdogg** [Aymkdn/v-snackbars#19]
Hi
Is there any reason why you keep storing snackbars data (objects, heights, keys, refs) despite they've been disposed already.

![Screenshot_1](https://user-images.githubusercontent.com/15647102/115215548-4852d680-a10c-11eb-9890-c8f5e6a2f753.jpg)

**Comment by Aymkdn** [comment]
In the next release I'll dispose `keys` and `heights`.

Regardings `$refs`, I don't really understand why it's still there. I can see it's `Array[0]`, so basically the reference exists but points to nothing. Maybe it's something to do with Vue? If you have any idea why, please feel free to share.

**Comment by tattdogg** [comment]
I'll play with the code. May be I'll find the reason.

**Comment by Aymkdn** [comment]
> I'll play with the code. May be I'll find the reason.

Thanks!

I've just released v3.2.2 for `keys` and `heights`.

**Comment by tattdogg** [comment]
From the official docs https://v3.vuejs.org/guide/migration/array-refs.html:

> In Vue 2, using the ref attribute inside v-for will populate the corresponding $refs property with an array of refs. This behavior becomes ambiguous and inefficient when there are nested v-fors present.

So it creates an array for each v-snackbar
After snackbar removing this array stays empty
So it makes sense to use static ref for all snackbars
`:ref="'v-snackbars-'+identifier"`
and use `idx` to get `$el`
`this.$refs['v-snackbars-'+this.identifier][idx].$el`

Could you please test this?
PR #20 

...or remove refs at all

**Comment by b-maslennikov** [comment]
#20

**Comment by Aymkdn** [comment]
It looks good! Thanks for your help :-)
