### ISSUE TITLE
feat-request: Add grouping option

### ISSUE THREAD

**Issue by neawbie** [Aymkdn/v-snackbars#23]
It would be great if you could group `snackbars` of the same type/message/etc, instead of having them show one by one.

Here is an example:

https://user-images.githubusercontent.com/26358211/128323758-9e085ec1-19cf-42df-bd0d-40a9cf07bde0.mov

This was taken from: https://quasar.dev/quasar-plugins/notify#grouping

You could send a new prop `group` that is boolean, to make the `snackbars` stack(default: `false`).

**Comment by Aymkdn** [comment]
Sorry but I won't implement it.

You could update the message by checking if a message is already available, and then increase the number. A very basic example: https://codesandbox.io/s/v-snackbars-with-increase-badge-s8uzn?file=/src/App.vue

You could make it prettier by using some badges in place of the "close" button, or whatever will look better.

**Comment by neawbie** [comment]
Thanks to your example and with slight modification to the code, I was able to implement it with badges.

https://user-images.githubusercontent.com/26358211/128855624-c83666b5-b19f-4497-aece-599c5da7e653.mov

I will leave the modified code below for others to see.

```javascript
<template>
  <v-app>
    <v-main class="text-center">
      <v-btn dark color="red" class="mt-6" @click="showMessage('red')">Click Me</v-btn>
      <v-btn dark color="blue" class="mt-6" @click="showMessage('blue')">Click Me</v-btn>

      <v-snackbars :objects.sync="objects" bottom left></v-snackbars>
    </v-main>
  </v-app>
</template>

<script>
import VSnackbars from "v-snackbars";

export default {
  name: "App",
  components: {
    "v-snackbars": VSnackbars,
  },
  data: () => ({
    objects: [],
  }),
  methods: {
    showMessage(toast) {
      const payload = {
        id: toast,
        timeout: 5000,
        color: toast,
      };
      let idx = this.objects.findIndex((obj) => obj.id === payload.id);
      if (idx > -1) {
        payload.count = this.objects[idx].count + 1;
        payload.message = `This snackbar has ${payload.count} message${
          payload.count > 1 ? "s" : ""
        }.`;
        this.objects.splice(idx, 1, payload);
      } else {
        payload.count = 1;
        payload.message = "This snackbar has 1 message.";
        this.objects.push(payload);
      }
    },
  },
};
</script>
```

To add the badge you just have to wrap _\<slot name="action" /\>_ with badge component, found inside **v-snackbars**.

```javascript
<v-badge
  :content="snackbar.count > 99 ? '99+' : snackbar.count"
  :value="snackbar.count"
  color="green"
  overlap
  :offset-x="snackbar.count > 9 ? snackbar.count > 99 ? '20px' : '10px' : '5px'"
  offset-y="5px">
  <slot
    name="action"
    :close="() => removeMessage(snackbar.key, true)"
    :id="snackbar.key"
    :index="idx"
    :message="snackbar.message">
    <v-btn text @click="removeMessage(snackbar.key, true)">close</v-btn>
  </slot>
</v-badge>
```
