### ISSUE TITLE
Prop dark does not work

### ISSUE THREAD

**Issue by kondr1** [Aymkdn/v-snackbars#24]
I think it is because color rewrites on this line [v-snackbars.vue#L158](https://github.com/Aymkdn/v-snackbars/blob/master/v-snackbars.vue)

**Comment by Aymkdn** [comment]
It might be. I'll have a look when I have the time (by Sunday night)

**Comment by Aymkdn** [comment]
Do you have some code examples? And the expected results? I'm not sure how it should look like…
