### ISSUE TITLE
Default props are not properly set, snackbars don't stack

### ISSUE THREAD

**Issue by nop33** [Aymkdn/v-snackbars#4]
Thanks for this component!

In the [_How to use_ section](https://github.com/Aymkdn/v-snackbars#how-to-use) of the README file you explain that the component can be used in its simplest form like this:
```
<v-snackbars :messages.sync="messages"></v-snackbars>
```

However, a few things go wrong:
1. I am getting the following error. It looks like there is no default color.
  ```
  Invalid prop: type check failed for prop "color"
  ```
2. The snackbars are not stacked. Find the link where I reproduce the problem below.

https://codesandbox.io/s/v-snackbars-demo-p8ctr?file=/src/App.vue

**Comment by Aymkdn** [comment]
Thanks for letting me know. It should now be OK with v2.1.1
